name: music_gen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pip:
    - tensorflow
    - magenta
    - music21
    - pretty-midi
    - flask
    - python-dotenv
    - note-seq
